### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by Ayubirad** [dagghe/PyOMA#18]
Hi there,
If at all feasible, please consider the following suggestions for improving this brilliant package:

1. The frequency domain procedures, all require the peak-picking means. Why not automate this procedure?
2. Could you also add another optional method for calculating damping in EFDD? like by fitting an exponential function to the relative maxima of the recorded decay.
3. A normalized averaged power spectral density (PSD) overlay on the stability diagram in the SSI procedures would make the choice of selecting the right frequencies rather easier, don't you think so?
4. Is it possible to add some indicators like mode complexity factor (MCF) to help the user in selecting the physical modes? This value will be between 0 (Real Mode) and 1 (Imaginary Mode). Therefore, for a real mode complexity should always be close to 0.

Best regards,

**Comment by dagghe** [comment]
Dear Ayubirad,

Thank you for your feedback! 
We are currently working on an update to the module so every comment/feedback is appreciated. 
I'll try now to address your comments:

1. The reason why the "picking of the peaks" is not automated is that we wanted to give the users the possibility to choose the peaks/modes that they judge as physical modes of the system. Imagine you're aware that one (or more) peak(s) is due to a source that is known to you (e.g. a rotating machinery) then you are really not interested in the properties of that peak (natural freq., damping, mode shape), however the "extraction" of these (not useful) results would increase the computation time. 
2. This is already what is happening: we are fitting a line on the logarithmic decrement, which is the same as fitting an exponential function to the peaks of decay signal (autocorrelation function). This is the way the EFDD algorithm (and the FSDD variation, which is the default method and which yields much better autocorrelation functions due to the filtering of the PSD) calculate the natural frequency and damping ratio.
3. I agree that it would make the reading of the stab. diag. easier. This should be fairly easy to implement and we will definitely consider adding this option in the coming update.
4. This should also be fairly easy to implement.

Again thanks for the interest in this module and for the feedback. 

Best regards,

Dag
