### ISSUE TITLE
AttributeError: module 'PyOMA' has no attribute 'FDDsvp'

### ISSUE THREAD

**Issue by braidoj** [dagghe/PyOMA#2]
Hi,

Using the "Example.py" file on Spyder (Python 3.9) gives the message:

"AttributeError: module 'PyOMA' has no attribute 'FDDsvp'"

**Comment by marco-rosso-m** [comment]
Hi, 

I solved the issues of importing after pip install by adding this [file](https://github.com/dagghe/PyOMA/blob/master/PyOMA/__init__.py).

So, after pip install the PyOMA module, in order to make it work when imported e.g. in Anaconda Spyder IDE, it is necessary look for the installed packages folder (C:\ProgramData\Anaconda3\Lib\site-packages\PyOMA) and paste here the file __init__.py . Now, when import PyOMA as oma in Spyder IDE it will work and load all the functions inside the PyOMA module.

**Comment by marco-rosso-m** [comment]
Hello, 

I have fixed the problem through the pip install command. Now it will directly install also the __init__.py file which is necessary to import the functions inside the PyOMA.py module.

Please refer to the command pip install Py-OMA published [here](https://pypi.org/project/Py-OMA/)
